In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["name","age","city","salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
df2['name']

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: str

In [11]:
df2['city']

0    New York
1       Paris
2      Berlin
3      London
Name: city, dtype: str

In [12]:
df2[['name','city']]

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London