In [5]:
import numpy as np
import pandas as pd

In [6]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["name","age","city","salary"]
df2 = pd.DataFrame(data_list,columns = columns)
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
df2['name']

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: str

In [10]:
df2['city']

0    New York
1       Paris
2      Berlin
3      London
Name: city, dtype: str

In [11]:
df2[['name','city']]

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [12]:
df2["fanatsy"] = ["anal","brutal","bbc","blacked"]

In [13]:
df2

    name  age      city  salary  fanatsy
0   John   28  New York   65000     anal
1   Anna   34     Paris   70000   brutal
2  Peter   29    Berlin   62000      bbc
3  Linda   42    London   85000  blacked

In [24]:
df2["friends"] = ["anshuman","tanmay","swastik","asit"]
df2[" fav pornstar"] = ["eva elfie", "alxy star","lary fox","eliaza ibrara"]
df2

   age      city  salary  fanatsy   friends   fav pornstar
0   28  New York   65000     anal  anshuman      eva elfie
1   34     Paris   70000   brutal    tanmay      alxy star
2   29    Berlin   62000      bbc   swastik       lary fox
3   42    London   85000  blacked      asit  eliaza ibrara

In [27]:
df2.drop("age",axis = 1,inplace = True)

In [28]:
df2

       city  salary  fanatsy   friends   fav pornstar
0  New York   65000     anal  anshuman      eva elfie
1     Paris   70000   brutal    tanmay      alxy star
2    Berlin   62000      bbc   swastik       lary fox
3    London   85000  blacked      asit  eliaza ibrara

In [31]:
df2.drop(0,axis = 0)

     city  salary  fanatsy  friends   fav pornstar
1   Paris   70000   brutal   tanmay      alxy star
2  Berlin   62000      bbc  swastik       lary fox
3  London   85000  blacked     asit  eliaza ibrara

In [32]:
df2

       city  salary  fanatsy   friends   fav pornstar
0  New York   65000     anal  anshuman      eva elfie
1     Paris   70000   brutal    tanmay      alxy star
2    Berlin   62000      bbc   swastik       lary fox
3    London   85000  blacked      asit  eliaza ibrara

In [34]:
df2.drop(3,axis =0,inplace = True)

In [35]:
df2

       city  salary fanatsy   friends  fav pornstar
0  New York   65000    anal  anshuman     eva elfie
1     Paris   70000  brutal    tanmay     alxy star
2    Berlin   62000     bbc   swastik      lary fox

In [44]:
df2.loc[[0,2]]

       city  salary fanatsy   friends  fav pornstar
0  New York   65000    anal  anshuman     eva elfie
2    Berlin   62000     bbc   swastik      lary fox

In [45]:
df2.loc[0]

city              New York
salary               65000
fanatsy               anal
friends           anshuman
 fav pornstar    eva elfie
Name: 0, dtype: object

In [48]:
df2.iloc[[0,2]]

       city  salary fanatsy   friends  fav pornstar
0  New York   65000    anal  anshuman     eva elfie
2    Berlin   62000     bbc   swastik      lary fox

In [49]:
df2

       city  salary fanatsy   friends  fav pornstar
0  New York   65000    anal  anshuman     eva elfie
1     Paris   70000  brutal    tanmay     alxy star
2    Berlin   62000     bbc   swastik      lary fox

In [63]:
df2.loc[[1,2]] [["friends"," fav pornstar"]]

   friends  fav pornstar
1   tanmay     alxy star
2  swastik      lary fox

In [64]:
df2.loc[[1,2]] [["city","salary"]]

     city  salary
1   Paris   70000
2  Berlin   62000

In [ ]:
# conditional slection

In [77]:
df2["size"] = [15,12,20]

In [78]:
df2

       city  salary fanatsy   friends  fav pornstar  size
0  New York   65000    anal  anshuman     eva elfie    15
1     Paris   70000  brutal    tanmay     alxy star    12
2    Berlin   62000     bbc   swastik      lary fox    20

In [79]:
df2[df2["size"] > 13]

       city  salary fanatsy   friends  fav pornstar  size
0  New York   65000    anal  anshuman     eva elfie    15
2    Berlin   62000     bbc   swastik      lary fox    20

In [83]:
df2[(df2["size"] > 13) & (df2["fanatsy"] == 'anal')]

       city  salary fanatsy   friends  fav pornstar  size
0  New York   65000    anal  anshuman     eva elfie    15