In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [8]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
#checking or finding the null value is along the column in the data frame is along the colums

In [7]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [10]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [11]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
# removing the null vaue is along the row in the data frame

In [12]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [14]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [17]:
df.dropna(thresh = 6)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [18]:
# filling the missing dta

In [19]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [21]:
#  but still if we print the df we will not get the replaced value of 0 inmplace of null value
#bcz only the ram has removed that valuer with 0 ans gave us the new data frame but the real one is not replaced 
#so we will use the inplace to do that change

In [30]:
# finding or checking and filling is along the columns wise and droping is row wise

In [27]:
values = { "A":0,"B":100,"C":300,"D":400}
df2 = df.fillna(value = values)
df2

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0