In [35]:
import numpy as np
import pandas as pd

In [39]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [40]:
df1.shape

(5, 3)

In [43]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [44]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [46]:
df1["A"] +10

0    20
1    20
2    20
3    20
4    20
Name: A, dtype: int64

In [50]:
# important thing "data frame applying function"

In [51]:
def square(x):
    return x**2

In [55]:
df1["B"] = df1["B"].apply(square)

In [56]:
df1

    A     B    C
0  10   100  100
1  10   400  200
2  10   900  300
3  10  1600  400
4  10  2500  500

In [58]:
df1["d"]= df1["B"].apply(square)

In [59]:
df1

    A     B    C        d
0  10   100  100    10000
1  10   400  200   160000
2  10   900  300   810000
3  10  1600  400  2560000
4  10  2500  500  6250000

SyntaxError: invalid syntax (2151504575.py, line 1)

In [48]:
df1

    A   B    C
0  10  10  100
1  10  20  200
2  10  30  300
3  10  40  400
4  10  50  500